spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/senior_test_db
    username: seu_username
    password: sua_senha
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
